### ISSUE TITLE
Black definition boxes sometimes don't fit the viewport.

### ISSUE THREAD

**Issue by ancarda** [dag/vlasisku#8]
Copied from https://bugs.launchpad.net/vlasisku/+bug/810601

http://screencast.com/t/AqI2rtRtE

Take that for example. It cannot be seen what's on the beginning of it.
Fix ideas:
- Make bubles more tall rather than wide: insert new line before each X sumti place.
- Insert some line breaks in the middle if the content length is more than a given number of characters.
- Check for actual window size and position bubble accordingly.
- Some or all of the above.

Or do you have some other ideas for fixing?

**Comment by Pendrokar** [comment]
Seems fixed with text wrapping in https://github.com/lojban/vlasisku/ repo, so this can be closed.
